# CLASE 07: PRODUCTO ESCALAR VECTOR

# 3. Producto por un escalar o multiplicación escalar-vector.

Otra operación es el *producto por un escalar* o *multiplicación escalar-vector* en la cual un vector es multiplicado por un escalar. La operación se hace elemento a elemento. Sea $\vec{v}$ un vector de $\mathbb{R}^{n}$ y $\alpha \in \mathbb{R}$. Si $\vec{x} = \alpha \vec{v}$ entonces:
$$
\vec{x} = \alpha \vec{v} =   \alpha\begin{bmatrix}v_{0}\\ v_{1}\\ \vdots \\ v_{n-1}\end{bmatrix} = \begin{bmatrix}\alpha \cdot v_{0}\\ \alpha \cdot v_{1}\\ \vdots \\ \alpha \cdot v_{n-1}\end{bmatrix}
$$

Por ejemplo, si $\vec{v} = (0,1,-2.3)$ y $\alpha = -1.1$ entonces $\alpha \vec{v} = (0,-1.1,2.53)$

In [1]:
# Se comprueba la operación 
print('0*-1.1: ', 0*1.1)
print('1*-1.1: ', 1*-1.1)
print('-2.3*-1.1: ', -2.3*-1.1)

0*-1.1:  0.0
1*-1.1:  -1.1
-2.3*-1.1:  2.53


## 3.1 Propiedades del producto por un escalar-vector

Sean $\vec{x},\vec{y}$ dos vectores y $\alpha, \beta$ dos escalares cualquiera. Las propiedades que cumple el producto escalar-vector son las siguientes:
* Conmutatividad: $\alpha \vec{x} = \vec{x}\alpha $

* Asociatividad: $(\beta \alpha)\vec{x} = \beta (\alpha\vec{x})$

* Distribución sobre suma escalar: $(\alpha + \beta)\vec{x} = \alpha \vec{x} + \beta\vec{x} =\beta\vec{x} + \alpha\vec{x} = \vec{x}(\alpha + \beta) $

* Distribución sobre suma de vectores: $\alpha (\vec{x}+\vec{y}) = \alpha\vec{x} + \alpha\vec{y}$

## 3.2 Algunas consideraciones

**Combinaciones lineales**. Sean $\vec{a}_{0},\vec{a}_{1},\dots,\vec{a}_{m-1}$ $n$-vectores y $\beta_{0},\beta_{1},\dots,\beta_{m-1}$ escalares entonces podemos definir el siguiente $n$-vector:

$$
\beta_{0}\vec{a}_{0}+\beta_{1}\vec{a}_{1}+\cdots+\beta_{m-1}\vec{a}_{m-1}
$$

Es llamado una *combinación lineal* de los vectores $\vec{a}_{0},\vec{a}_{1},\dots,\vec{a}_{m-1}$. Los escalares $\beta_{0},\beta_{1},\dots,\beta_{m-1}$ son llamados los *coeficientes* de la combinación lineal.

**Combinaciones lineales de vectores unitarios**. Es posible escribir cualquier $\vec{b}$ $n$-vector como combinación lineal de los vectores unitarios estándar:

$$
\vec{b} = b_{0}\hat{e}_{0}+b_{1}\hat{e}_{1} + \cdots +b_{n-1}\hat{e}_{n-1}
$$

Con $b_{i}$ escalares y $\hat{e}_{i}$ el i-ésimo vector unitario. Un ejemplo específico sería:

$$
\begin{bmatrix}1\\ -1\\ 0\end{bmatrix} = (1)\begin{bmatrix}1\\ 0\\ 0\end{bmatrix} + (-1)\begin{bmatrix}0\\ 1\\ 0\end{bmatrix} + (0)\begin{bmatrix}0\\ 0\\ 1\end{bmatrix}
$$

Como nota final aquí, notemos que si el espacio vectorial es de dimensión $n$ entonces tiene $n$ vectores unitarios $\hat{e}_{i}$


**Combinaciones lineales especiales**. Algunas combinaciones de $n$-vectores $\vec{a}_{0},\vec{a}_{1},\dots,\vec{a}_{m-1}$ tienen nombres especiales.  Por ejemplo, si los coeficientes de la combinación lineal son tales que $\beta_{0}=\beta_{1}=\cdots=\beta_{m-1} = 1$ entonces simplemente es una suma de vectores. Si en cambio $\beta_{0}=\beta_{1}=\cdots=\beta_{m-1} = 1/m$ entonces la combinación lineal se llama el *promedio de vectores*.       
Cuando $\beta_{0}+\beta_{1}+\cdots+\beta_{m-1}=1$ entonces la combinación lineal se llama *combinación afín*, cuando los coeficientes $\beta_{i}$ son no-negativos entonces la combinación lineal es llamada una *mezcla*, *combinación convexa* o un *promedio pesado*.

# CLASE 08: PRODUCTO ESCALAR-VECTOR EN PYTHON

## 3.3 Producto por un escalar-vector en Python

Desde la clase pasada introducimos Numpy para manejo de vectores. Una de las fortunas de usar numpy sobre listas es la simpleta de este tipo de operaciones. Realizar esta operación será tan sencillo como usar el operador $*$. 

In [1]:
# Se muestra la opéración sin usar la librería de Python
a = [1,1,1]
print(a*3)

[1, 1, 1, 1, 1, 1, 1, 1, 1]


Sin la librería de numpy, la multiplicación de vector por escalar, resultar en el concatenación de n veces el escalar del vector, lo cuál matemáticamente no es correcto.

Partamos del vector $\vec{x}= (1,-1,1)$ y del escalar $a = 3.1$ entonces, realicemos las operaciones $a\vec{x}$ y $\vec{x}a$

In [2]:
# Se importa las librerías necesarias
import numpy as np

In [3]:
# Se declara el vector x y el escalar a
x = np.array([1,-1,1])
a = 3.1

# Se comprueba la propiedad conmutativa
print('ax es:\n', a*x)
print('xa es:\n', x*a)

ax es:
 [ 3.1 -3.1  3.1]
xa es:
 [ 3.1 -3.1  3.1]


Se compruba la propiedad conmutativa de la multiplicación de un escalar por un vector, ahora se realiza la propiedad distributiva sobre suma escalar.

In [4]:
# Se crea otro escalar
b = -a

# Se comprueba la propiedad distributiva sobre suma de escalares
print('(a+b)*x es: \n', (a + b)*x)
print('a*x + b*x: \n', a*x + b*x)

(a+b)*x es: 
 [ 0. -0.  0.]
a*x + b*x: 
 [0. 0. 0.]


Se comprueba la propiedad distributiva sobre suma de escalares. 

Se con considera el sigueinte vector mas tres escalares

$$
\vec{v} = (1,1)\newline
\alpha = -1\newline
\beta = 2\newline
\gamma = 0.1
$$

In [5]:
# Se define el vector
v = np.array([1,1])
# Se define los escalares
alpha = -1
beta = 2
gamma = 0.1

# Algunas operaciones
print('v*alpha:\n', v*alpha)
print('v*beta:\n', v*beta)
print('v*gamma:\n', v*gamma)

v*alpha:
 [-1 -1]
v*beta:
 [2 2]
v*gamma:
 [0.1 0.1]


Para representar estos valores geometricamente se recurre a la página de [GeoGebra](https://geogebra.org/calculator), inicialmente se tiene el vector que se representa geometricamente como:

![](imagenes/img1.png)

Ahora se muestran los vector multiplicado por los escalares, siendo v el vector de v(alpha), w el vector de v(beta) y a el vector multiplicado por v(gamma)

![](imagenes/img2.png)

El vector multiplicado por un escalar negativo cambia la dirección del vector. Al multiplicar por un escalar mayor que uno se obtiene un vector (w) mas grande, mientras que al multiplicar por un número menor que 1, se obtiene un vector (a) mas corto. Por tanto el escalar va a afectar el vector, amplificandolo, comprimiendolo o cambiandole el sentido.

## 3.3 Ejercicios

**Problema 1**. Escribe TODOS los vectores unitarios estándar de $\mathbb{R}^{4}$. *Hint:* son cuatro. 

**Solución:**

$$
\hat{e}_{0}=\begin{bmatrix} 1\\ 0\\ 0\\ 0\end{bmatrix}\ 
\hat{e}_{1}=\begin{bmatrix} 0\\ 1\\ 0\\ 0\end{bmatrix}\ 
\hat{e}_{2}=\begin{bmatrix} 0\\ 0\\ 1\\ 0\end{bmatrix}\ 
\hat{e}_{3}=\begin{bmatrix} 0\\ 0\\ 0\\ 1\end{bmatrix}
$$

**Problema 2**. Escribe tres combinaciones lineales de vectores en $\mathbb{R}^{3}$ para expresar el vector $[1,1,1]$.

**Solución:**

In [6]:
# Vector
v = np.array([1,1,1])

# Escalares
alpha = -1
beta = 2
gamma = 0.5

print('vector:\n', v)
#Combinación
print('Combinación:\n', alpha*v + beta*v + gamma*v)

vector:
 [1 1 1]
Combinación:
 [1.5 1.5 1.5]


**Problema 3.** Escribe tres combinaciones afines con vectores de $\mathbb{R}^{3}$ donde $\beta_{0}\neq\beta_{1}\neq\beta_{2}$ pero que se cumpla que $\beta_{0}+\beta_{1}+\beta_{2}=1$. *HINT*: Si no se te ocurre ninguna combinación para los coeficientes la ecuación $\beta_{0}+\beta_{1}+\beta_{2}=1$ tiene infinitas soluciones, puedes hacer un programa para encontrar tres. 

In [7]:
a = np.linspace(0, 5, 1000)

In [10]:
a[1] - a[0]

0.005005005005005005

In [11]:
a[2] - a[1]

0.005005005005005005

In [12]:
a[999] - a[998]

0.005005005005005003

In [13]:
a[0]

0.0

In [14]:
a[999]

5.0

**Solución**

In [18]:
[b0, b1] = np.random.rand(2)
b2 = 1 - b0 - b1
print('b0: ', b0, 'b1: ', b1, 'b2: ', b2)

b0:  0.3365595469327308 b1:  0.09683604139223456 b2:  0.5666044116750346


## Enlaces Externos

[GeoGebra](https://geogebra.org/calculator)

[Colab Original](https://colab.research.google.com/drive/1uF1QvMQBR9B-UPPUKg8d4DVuZNROqUA_?usp=sharing)